name: Api Release
on:
  push:
    branches: [ "master" ]
    paths:
    - 'QuickTest.Api/**'
    - '.github/workflows/api-release.yml'
jobs:
  nugetCreate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Adjust NuGet Config Credentials
        run: |
          cp ./nuget.bak ./NuGet.config
          echo $(sed -e "s@\${PAT}@${{ secrets.NUGET_TOKEN }}@" NuGet.config) > NuGet.config
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.Docker_Username}}
        password: ${{secrets.Docker_Password}}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./QuickTest.Api/Dockerfile
        push: true
        tags: ${{secrets.Docker_Username}}/quick-test-api:latest
