# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  find_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get version
      id: package_version
      uses: KageKirin/get-csproj-version@v1.0.0
      with:
        file: QuickTest.Data/QuickTest.Data.csproj
    - name: Print
      run: echo ${{ steps.test.package_version.version }}
      
  deploy:
    needs: find_version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Package Setup
      run: dotnet nuget add source --username aelmendorf --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Sensor-Electronic-Technology/index.json"
    - name: Package
      run: dotnet pack --configuration Release
    - name: Publish
      run: dotnet nuget push "bin/Release/QuickTest.Data.${{ steps.test.package_version.version }}.nupkg" --source "github"
   
