@QuickTest.Api_HostAddress = http://localhost:5260
@Remote.Api_HostAddress = http://172.20.4.206

### GET request to get initial data
GET {{QuickTest.Api_HostAddress}}/api/qt_results/B03-2615-07
Accept: text/plain

### GET request to get initial data
GET http://172.20.4.206/api/results/all/excel/B03-2615-07?1
Accept: text/plain

### GET request to get initial data
GET {{QuickTest.Api_HostAddress}}/api/results/all/excel/B01-3766-06
Accept: text/plain

### GET request for quick-test list
GET {{Remote.Api_HostAddress}}/api/quick-tests/list-since/5-1-2024
Accept: text/plain

### GET request to get initial data
GET http://172.20.4.206/api/results/excel/B01-3277-28?1
Accept: application/json

### GET request to get all wafer pads
GET {{QuickTest.Api_HostAddress}}/api/wafer_pads/2
Accept: application/json

### GET request to get all wafer pads
GET {{QuickTest.Api_HostAddress}}/api/map/2
Accept: application/json

### GET request to get all wafer pads-external
GET http://172.20.4.206/api/map/2
Accept: application/json

### GET request test
GET http://172.20.4.206/api/results/excel/B06-1393-?1
Accept: application/json

### GET request test
GET {{Remote.Api_HostAddress}}/api/quick-test/exists/B01-3277-28
Accept: application/json

### GET request test

GET {{Remote.Api_HostAddress}}/api/map/2
Accept: application/json
